parameters:
  cors.config:
    enabled: true
    allowedMethods: ['GET', 'OPTIONS']
    allowedHeaders:
      - 'Content-Type'
      - 'Accept'
      - 'Authorization'
    allowedOrigins:
      - 'http://localhost:3000'
      - 'http://localhost:5173'
      - 'http://192.168.1.157:9023'
      - 'https://talknotes.codenil.online'
    exposedHeaders: false
    maxAge: 1000
    supportsCredentials: false
  twig.config:
    debug: false
    auto_reload: false
    cache: true
