<?php

use Drupal\node\Entity\Node;

function get_cat($name) {
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')
    ->loadByProperties(['vid' => 'main_categories', 'name' => $name]);
  return $terms ? reset($terms)->id() : NULL;
}

$entries = [
  ['title' => 'Touch base', 'category' => 'Business Lingo', 'short_meaning' => 'To briefly connect or check in with someone about a topic or project.', 'detailed_explanation' => '"Touch base" means to have a brief, informal check-in with someone — usually to share a quick update, confirm something, or stay connected on a project. It does not imply a long formal meeting.', 'usage_examples' => '"Let\'s touch base tomorrow morning before the client call." | "I wanted to touch base with you about the status of the report."', 'notes' => 'This is a sports metaphor from baseball, where a runner must touch each base. In business it has come to mean making brief contact. One of the most commonly used phrases in American corporate culture.'],
  ['title' => 'Ping me', 'category' => 'Business Lingo', 'short_meaning' => 'Send me a quick message to get my attention or follow up.', 'detailed_explanation' => '"Ping me" comes from networking terminology — a ping is a small signal sent to check if a server is reachable. In everyday workplace language, it means send a quick message, often via Slack, email, or text.', 'usage_examples' => '"Ping me when you\'re ready to review." | "If you have questions, ping me on Slack."', 'notes' => 'Very common in tech companies and modern workplaces that use Slack or Teams. Less common in traditional industries. It implies a quick, low-effort message rather than a formal communication.'],
  ['title' => 'Move the needle', 'category' => 'Business Lingo', 'short_meaning' => 'To make a meaningful, measurable difference or progress toward a goal.', 'detailed_explanation' => '"Moving the needle" means making a significant enough impact that it shows up in your metrics or results — like a needle moving on a gauge. If something doesn\'t move the needle, it means it has no real measurable effect.', 'usage_examples' => '"We\'ve tried three different approaches, but nothing is really moving the needle on customer satisfaction." | "This campaign finally moved the needle — sign-ups are up 40%."', 'notes' => 'The metaphor comes from analog gauges and dials where a physical needle indicates a reading. It is widely used in business, marketing, and politics.'],
  ['title' => 'You bet', 'category' => 'American Lingo', 'short_meaning' => 'Absolutely yes; of course; used to enthusiastically confirm or agree.', 'detailed_explanation' => '"You bet" is a very American expression of enthusiastic agreement or confirmation. It can replace "yes," "of course," or "absolutely." It has a warm, friendly, informal tone.', 'usage_examples' => '"Will you be at the meeting tomorrow?" → "You bet!" | "Thanks for staying late." → "You bet — happy to help."', 'notes' => 'This phrase is more common in the Midwest and Southern United States but is understood everywhere. It sounds natural and friendly. Non-native speakers sometimes find it confusing because it has nothing to do with gambling.'],
  ['title' => 'Sounds good', 'category' => 'American Lingo', 'short_meaning' => 'That works for me; I agree; I am okay with that plan.', 'detailed_explanation' => '"Sounds good" is one of the most versatile and commonly used phrases in American casual and professional communication. It signals agreement, acceptance, or approval of a plan or suggestion without being overly formal.', 'usage_examples' => '"Can we meet at 3 PM?" → "Sounds good!" | "I\'ll send you the draft by end of day." → "Sounds good, thanks."', 'notes' => 'You will hear "sounds good" dozens of times in any American workplace in a single day. It is neutral, friendly, and works in both formal and informal contexts. Often used in emails and text messages as well.'],
  ['title' => 'Have a good one', 'category' => 'Everyday American Expressions', 'short_meaning' => 'A casual farewell meaning "have a good day" or "have a good time."', 'detailed_explanation' => '"Have a good one" is a very common casual American goodbye. The "one" can refer to the rest of the day, the weekend, a vacation, or whatever is coming next. It is shorter and slightly more informal than "have a good day."', 'usage_examples' => 'Cashier after checkout: "Have a good one!" | Leaving work: "Alright, have a good one — see you tomorrow!"', 'notes' => 'This is one of those automatic American social expressions that you will hear constantly in everyday life — at stores, offices, schools, and anywhere people say goodbye. Responding with "you too!" is the standard reply.'],
  ['title' => 'How\'s it going?', 'category' => 'Everyday American Expressions', 'short_meaning' => 'A casual greeting similar to "how are you?" — usually not expecting a detailed answer.', 'detailed_explanation' => '"How\'s it going?" is one of the most common American greetings. Despite sounding like a question, it is usually a social greeting rather than a genuine inquiry. The expected response is brief and positive, not a detailed report on how things are actually going.', 'usage_examples' => 'Passing a coworker: "Hey, how\'s it going?" → "Good, thanks! You?" | Starting a call: "How\'s it going on your end?"', 'notes' => 'New arrivals to the US sometimes make the mistake of giving a detailed honest answer to this question. In most casual contexts, "good, thanks" or "pretty good, how about you?" is the expected response. However, if someone sits down and sincerely asks, they may actually want to know.'],
  ['title' => 'Just checking in', 'category' => 'Politeness and Tone', 'short_meaning' => 'A polite way to follow up or ask for an update without sounding demanding.', 'detailed_explanation' => '"Just checking in" is a very common phrase in American professional communication, especially in emails. It softens a follow-up by framing it as casual interest rather than pressure. It is often used when you have not received a reply and want to ask politely.', 'usage_examples' => '"Just checking in to see if you had a chance to review my proposal." | "Hi, just checking in on the status of the order — let me know if you need anything from my end."', 'notes' => 'The word "just" here softens the message and makes it feel less demanding. This is a very useful phrase to know for professional email communication in the US. Without it, a follow-up can sound pushy; with it, it sounds considerate.'],
  ['title' => 'When you get a chance', 'category' => 'Politeness and Tone', 'short_meaning' => 'Please do this when you have time — it is not urgent, but I am making a request.', 'detailed_explanation' => '"When you get a chance" is a polite way to make a non-urgent request. It signals that you are not demanding immediate action, but you are still making a clear request. It is softer than saying "please do this" and respects the other person\'s time.', 'usage_examples' => '"When you get a chance, could you take a look at the updated spreadsheet?" | "When you get a chance, I\'d love your feedback on this draft."', 'notes' => 'Americans use softening phrases like this frequently in professional settings to maintain good relationships. If something is actually urgent, you would use different language — "when you get a chance" signals low urgency.'],
  ['title' => 'Nuance', 'category' => 'Vocabulary', 'short_meaning' => 'A subtle difference or distinction in meaning, expression, or sound.', 'detailed_explanation' => '"Nuance" refers to a very subtle shade of difference — in meaning, tone, color, or feeling — that is easy to miss but important to understand. Something with nuance has layers and complexity that go beyond the obvious.', 'usage_examples' => '"The translation captured the meaning but lost the nuance of the original poem." | "There is a lot of nuance in this situation — it is not as simple as it looks."', 'notes' => 'Borrowed from French, where it originally referred to shades of color. Now used widely in English to describe subtle complexity in any domain. A very useful word for discussing language, culture, politics, and art.'],
  ['title' => 'Resilient', 'category' => 'Vocabulary', 'short_meaning' => 'Able to recover quickly from difficulties; tough and adaptable.', 'detailed_explanation' => '"Resilient" describes someone or something that bounces back after setbacks, stress, or adversity. In people, it refers to emotional and psychological strength. In materials, it describes the ability to spring back to shape after being bent or compressed.', 'usage_examples' => '"She has been incredibly resilient through a very difficult year." | "We need to build a more resilient supply chain that can handle disruptions."', 'notes' => 'This has become one of the most important words in modern American business and education language. Schools explicitly teach "resilience" as a life skill. It is also heavily used in organizational and leadership discussions.'],
  ['title' => 'Pragmatic', 'category' => 'Vocabulary', 'short_meaning' => 'Dealing with things sensibly and realistically, based on practical considerations rather than theory or ideals.', 'detailed_explanation' => '"Pragmatic" describes a practical, realistic approach to problems — focusing on what actually works rather than what is theoretically ideal. A pragmatic person makes decisions based on real-world conditions and outcomes.', 'usage_examples' => '"We need to be pragmatic about the timeline — ideally we would have six months, but we have three." | "She takes a very pragmatic approach to problem-solving."', 'notes' => 'Often used as a positive quality in American business culture. Being "pragmatic" is generally respected — it means you are sensible and results-oriented rather than rigid or idealistic.'],
  ['title' => 'Playdate', 'category' => 'Kids and School English', 'short_meaning' => 'A planned social get-together arranged by parents for young children to play together.', 'detailed_explanation' => 'A playdate is when parents schedule time for their young children to spend together, either at home or at a park or activity. It is a very common part of American childhood and parenting culture. Unlike spontaneous play, a playdate is pre-arranged.', 'usage_examples' => '"Can Emma come over for a playdate on Saturday afternoon?" | "We set up a playdate at the park so the kids could run around together."', 'notes' => 'The term "playdate" itself can sound surprisingly formal to people from other cultures, where children simply went outside and played with neighborhood kids. In American suburbs today, children\'s social time is often more structured and scheduled by parents.'],
  ['title' => 'Permission slip', 'category' => 'Kids and School English', 'short_meaning' => 'A form sent home from school that parents must sign to give permission for their child to participate in an activity.', 'detailed_explanation' => 'A permission slip is a paper form (or sometimes digital form) sent by schools asking parents to officially authorize their child to go on a field trip, participate in a special event, or be photographed. Without a signed permission slip, the child typically cannot participate.', 'usage_examples' => '"The permission slip for the science museum trip is due this Friday." | "I forgot to sign the permission slip and had to email it from work."', 'notes' => 'Permission slips are a standard and very common part of American school life. Parents should expect to receive them throughout the school year. Schools keep signed permission slips on file for legal and safety reasons.'],
  ['title' => 'Today itself', 'category' => 'Literal Translation Traps', 'short_meaning' => '"Today itself" is a direct translation from Indian languages meaning "today, specifically" or "today without delay." It sounds unnatural in American English.', 'detailed_explanation' => 'In several Indian languages, adding a word equivalent to "itself" after a time word adds emphasis — meaning "specifically today" or "today and not later." When translated directly into English, it sounds unusual to American ears. Americans would simply say "today" or add "by end of day" for emphasis.', 'usage_examples' => 'Indian English: "I need this today itself." | American English: "I need this today." or "I need this by end of day today."', 'notes' => 'Other similar translations: "now itself" (should be "right now"), "here itself" (should be "right here"). These constructions make perfect sense in Hindi, Bengali, and other Indian languages but sound unusual in English.'],
  ['title' => 'Discuss about', 'category' => 'Literal Translation Traps', 'short_meaning' => '"Discuss about" is grammatically incorrect in English — "discuss" already includes the meaning of "about."', 'detailed_explanation' => 'In many Indian languages, the verb for "discuss" requires an equivalent of "about" after it. When translated directly, this produces "discuss about" in English. However, in English, "discuss" is a transitive verb that takes a direct object — you discuss something, not discuss about something.', 'usage_examples' => 'Incorrect: "Let us discuss about the project timeline." | Correct: "Let us discuss the project timeline." or "Let us talk about the project timeline."', 'notes' => 'This is a very common error in Indian English writing and speaking. Similarly, "mention about" should be just "mention," and "explain about" should be just "explain." The pattern is: transitive verbs in English do not need "about."'],
];

$created = 0;
foreach ($entries as $entry) {
  $cat_id = get_cat($entry['category']);
  if (!$cat_id) { echo "Category not found: {$entry['category']}\n"; continue; }
  $node = Node::create([
    'type' => 'language_entry',
    'title' => $entry['title'],
    'status' => 1,
    'moderation_state' => 'published',
    'field_main_category' => ['target_id' => $cat_id],
    'field_short_meaning' => $entry['short_meaning'],
    'field_detailed_explanation' => ['value' => $entry['detailed_explanation'], 'format' => 'basic_html'],
    'field_usage_examples' => ['value' => $entry['usage_examples'], 'format' => 'basic_html'],
    'field_notes_background' => ['value' => $entry['notes'], 'format' => 'basic_html'],
  ]);
  $node->save();
  $created++;
  echo "Created: {$entry['title']}\n";
}
echo "\n$created entries created!\n";
