<?php

use Drupal\node\Entity\Node;

function get_cat($name) {
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')
    ->loadByProperties(['vid' => 'main_categories', 'name' => $name]);
  return $terms ? reset($terms)->id() : NULL;
}

function make_entry($title, $category, $short, $explanation, $examples, $notes) {
  $cat_id = get_cat($category);
  if (!$cat_id) { echo "Category not found: $category\n"; return; }
  $existing = \Drupal::entityTypeManager()->getStorage('node')
    ->loadByProperties(['type' => 'language_entry', 'title' => $title]);
  if ($existing) { echo "Skip (exists): $title\n"; return; }
  Node::create([
    'type' => 'language_entry',
    'title' => $title,
    'status' => 1,
    'moderation_state' => 'published',
    'field_main_category' => ['target_id' => $cat_id],
    'field_short_meaning' => $short,
    'field_detailed_explanation' => ['value' => $explanation, 'format' => 'basic_html'],
    'field_usage_examples' => ['value' => $examples, 'format' => 'basic_html'],
    'field_notes_background' => ['value' => $notes, 'format' => 'basic_html'],
  ])->save();
  echo "Created: $title\n";
}

// ── Business Lingo ────────────────────────────────────────────
make_entry('Deep dive', 'Business Lingo', 'A thorough, detailed examination of a topic.', 'A "deep dive" means going beyond the surface level to examine something thoroughly and in detail. It implies spending significant time and effort to truly understand a subject, rather than just getting a quick overview.', '"Let\'s do a deep dive into the customer feedback before we redesign the app." | "The board wants a deep dive into why sales dropped last quarter."', 'Originally a scuba diving term. Now one of the most common phrases in corporate meetings. Often used as a verb: "Let\'s deep dive into this."');

make_entry('Boil the ocean', 'Business Lingo', 'To try to do something impossibly large or complex all at once, rather than starting with something manageable.', '"Boiling the ocean" is used to warn against taking on an unrealistically large or complex task all at once. It is usually said to encourage someone to narrow their scope and start smaller.', '"We don\'t need to boil the ocean here — let\'s just fix the three biggest problems first." | "Your proposal is great but you\'re trying to boil the ocean. Pick one market to start."', 'A vivid metaphor — it would be impossible to actually boil an entire ocean. Used as a gentle pushback when someone\'s plan is too ambitious in scope.');

make_entry('Synergy', 'Business Lingo', 'The combined effect of two things working together that is greater than the sum of their parts.', '"Synergy" is a business buzzword describing situations where combining two people, teams, or companies creates more value than each would produce separately. Often used in merger and acquisition discussions.', '"The merger will create real synergy between our marketing teams." | "We see strong synergy between your technology and our distribution network."', 'One of the most overused and sometimes mocked words in corporate language. When people want to sound strategic without saying much, they often reach for "synergy." Use it sparingly.');

make_entry('Circle the wagons', 'Business Lingo', 'To gather together as a group to defend against an outside threat or criticism.', '"Circling the wagons" means pulling together, closing ranks, and presenting a unified front against an external challenge. It often implies a defensive posture.', '"After the negative press coverage, the company circled the wagons and went into crisis mode." | "Let\'s circle the wagons before the audit — make sure everyone is aligned."', 'From the American frontier, where pioneers would arrange their covered wagons in a circle to defend against attack. Now used in business to describe defensive group behavior.');

make_entry('Drinking the Kool-Aid', 'Business Lingo', 'Blindly following or believing in a company, leader, or ideology without critical thinking.', '"Drinking the Kool-Aid" refers to unquestioning belief or loyalty to a company, brand, ideology, or leader — often used critically to suggest someone has lost their objectivity.', '"Everyone at that startup has drunk the Kool-Aid — they think their app will change the world." | "I\'m worried the team is just drinking the Kool-Aid instead of honestly evaluating the product."', 'This phrase has a dark origin — it references the 1978 Jonestown tragedy. In business it is used more casually, but some people find it inappropriate given its origins.');

make_entry('At the end of the day', 'Business Lingo', 'Ultimately; when everything is considered; what really matters most.', '"At the end of the day" is a filler phrase used to introduce the most important point or conclusion. It signals that the speaker is cutting through all the details to state what truly matters.', '"At the end of the day, what the customer wants is a product that just works." | "We can debate the details, but at the end of the day, we need to hit the deadline."', 'Extremely common in business speech. Some consider it an overused filler. It rarely has anything to do with the literal end of a working day.');

make_entry('Put it on the back burner', 'Business Lingo', 'To postpone or deprioritize something to deal with later.', 'Putting something "on the back burner" means setting it aside temporarily to focus on more urgent priorities. It comes from cooking, where you move a pot to a back burner when it needs less attention.', '"Let\'s put the website redesign on the back burner until after the product launch." | "That idea is interesting but we\'re putting it on the back burner for now."', 'A cooking metaphor. The front burners on a stove are where you cook things actively; the back burners are for things that can simmer unattended. Very common in workplace prioritization discussions.');

make_entry('Leverage', 'Business Lingo', 'To use something to maximum advantage; to make use of an asset or advantage.', 'In business, "leverage" as a verb means to use a resource, relationship, skill, or advantage strategically to get the best outcome. It implies using what you have in a smart, amplified way.', '"We should leverage our existing customer base to launch the new product." | "Can we leverage our partnership with that agency to get better rates?"', 'Originally a financial term referring to using borrowed money to amplify returns. Now used broadly to mean using any kind of advantage. Some find it overused corporate jargon.');

make_entry('Deliverable', 'Business Lingo', 'A specific, tangible output or result that must be produced by a specific time.', 'A "deliverable" is something concrete that you commit to producing and handing over — a document, a report, a prototype, a presentation. It is a project management term that emphasizes the specific, measurable nature of what is being produced.', '"The deliverables for this phase are: a market analysis, a competitive review, and a pricing recommendation." | "What are your deliverables for this sprint?"', 'Essential vocabulary in project management, consulting, and agency work. If someone asks you for your deliverables, they want to know specifically what you will produce and by when.');

make_entry('Action item', 'Business Lingo', 'A specific task assigned to someone that must be completed, usually coming out of a meeting.', 'An "action item" is a concrete task that someone is responsible for completing after a meeting or discussion. Good meetings usually end with clear action items — who will do what by when.', '"Let\'s make sure we capture the action items before we close this meeting." | "My action item from today is to follow up with the vendor by Thursday."', 'A core concept in effective meeting management. Without action items, meetings often feel like discussions that lead nowhere. Writing them down with an owner and a deadline is considered best practice.');

// ── American Lingo ────────────────────────────────────────────
make_entry('Ballpark figure', 'American Lingo', 'A rough, approximate estimate — not exact, but in the right general range.', 'A "ballpark figure" is an approximate number or estimate. It is not meant to be precise, but to give a general sense of scale or range. The phrase comes from baseball — a ballpark is large enough that a ball landing anywhere inside it is "in the ballpark."', '"Can you give me a ballpark figure for how long this project will take?" | "The ballpark cost is somewhere between $10,000 and $15,000, but we\'ll need more details for an exact quote."', 'Baseball metaphor. If something is "in the ballpark," it is approximately right. Very common in American business and everyday conversation when precision is not yet possible or needed.');

make_entry('Rain check', 'American Lingo', 'A promise to take up an offer at a later time because you cannot accept it now.', 'A "rain check" is an informal commitment to do something later that you cannot do right now. It is a polite way of declining an invitation while expressing interest in doing it another time.', '"I can\'t make it to dinner tonight, but can I take a rain check?" | "We\'re sold out of that item, but we can give you a rain check to buy it at the sale price when it\'s back in stock."', 'Originally a literal ticket given to baseball fans when a game was rained out, allowing them to attend a future game. Now used broadly for any deferred offer or commitment.');

make_entry('On the fence', 'American Lingo', 'Undecided; not having made up one\'s mind yet about something.', 'Being "on the fence" means you have not yet decided which side you are on — you are sitting between two options without committing to either. It implies genuine indecision rather than intentional avoidance.', '"I\'m still on the fence about whether to take the job offer." | "Half the team is on the fence about the new policy — they haven\'t decided if they support it yet."', 'The image is of sitting on a fence between two fields — you have not yet chosen which one to go into. A very common American expression for indecision on any topic.');

make_entry('Bite the bullet', 'American Lingo', 'To endure a painful or difficult situation with courage and without complaining.', '"Biting the bullet" means accepting something difficult, unpleasant, or unavoidable and just pushing through it. It implies stoicism and getting something hard over with.', '"I\'ve been putting off the dentist for months — I just need to bite the bullet and make the appointment." | "We\'re going to have to bite the bullet and cut our budget by 20%."', 'Historically, soldiers would bite on a bullet during painful medical procedures before anesthesia was common. Now used broadly for any situation where you must endure something difficult.');

make_entry('Hit the ground running', 'American Lingo', 'To start something with energy and momentum, achieving results immediately without needing time to prepare.', '"Hitting the ground running" means starting something — a new job, a project, a relationship — with immediate energy and productivity. No warm-up period is needed.', '"She hit the ground running at her new job and led a major project in her first week." | "We need someone who can hit the ground running — we don\'t have time to train from scratch."', 'The phrase evokes the image of someone who is moving so fast they are already running when they land. Common in job descriptions and when discussing starting new ventures.');

make_entry('Under the weather', 'American Lingo', 'Feeling sick or not well.', '"Under the weather" is a very common American expression for feeling ill or unwell. It is often used when the illness is minor — a cold, a headache, a stomach ache — rather than something serious.', '"I\'m feeling a little under the weather today, so I might leave work early." | "Sorry I missed the meeting — I\'ve been under the weather all week."', 'The nautical origin suggests that sailors feeling seasick would go below deck, which was literally "under the weather" (the weather deck was the main deck exposed to the elements). Now widely used for any mild illness.');

make_entry('Beat around the bush', 'American Lingo', 'To avoid getting to the main point; to talk around a subject without addressing it directly.', '"Beating around the bush" means avoiding the main subject, being indirect, or taking a long time to get to the point. It is often used as a complaint about someone being evasive.', '"Stop beating around the bush — just tell me if you got the job or not." | "She beat around the bush for ten minutes before finally admitting she needed money."', 'Origin from hunting — beaters would beat the bushes to flush out birds for hunters, going around the edges without directly going into the bush. Now it means any kind of indirect approach to a difficult topic.');

make_entry('The ball is in your court', 'American Lingo', 'It is now your turn to take action or make a decision.', '"The ball is in your court" means the next move or decision belongs to the other person. You have done what you need to do, and now they must respond or act.', '"I\'ve sent over the proposal — the ball is in their court now." | "I\'ve made my offer. The ball is in your court."', 'A tennis metaphor. When the ball is on your side of the net, it is your responsibility to hit it back. Very common in negotiations, job hunting, and any situation where turns are taken.');

// ── Idioms and Phrases ────────────────────────────────────────
make_entry('Cost an arm and a leg', 'Idioms and Phrases', 'To be extremely expensive.', '"Costing an arm and a leg" means something is very, very expensive — the price is almost unimaginably high. It is always used hyperbolically.', '"That new phone costs an arm and a leg, but everyone seems to want one." | "Hiring a good lawyer in this city will cost you an arm and a leg."', 'The origin is unclear but the phrase dates to the mid-20th century. The idea is that the price is so high you would have to give up something as valuable as a limb to pay for it.');

make_entry('Once in a blue moon', 'Idioms and Phrases', 'Very rarely; something that almost never happens.', '"Once in a blue moon" describes something that happens very infrequently — so rarely that it is almost unusual when it does occur. A "blue moon" historically referred to the rare occurrence of a second full moon in a single calendar month.', '"My brother calls me once in a blue moon — maybe twice a year." | "It rains here once in a blue moon, so when it does, everyone panics."', 'A blue moon (second full moon in a month) actually occurs roughly every 2-3 years, making it genuinely rare. The phrase captures that sense of real but uncommon occurrence.');

make_entry('Kill two birds with one stone', 'Idioms and Phrases', 'To accomplish two things with a single action.', '"Killing two birds with one stone" means accomplishing two goals or solving two problems simultaneously with one effort. It emphasizes efficiency — getting double the value from a single action.', '"I need to go to the post office and the bank — I\'ll kill two birds with one stone since they\'re both on Main Street." | "Taking that course will help with both my certification and my job application — it kills two birds with one stone."', 'Despite the violent imagery, this idiom is used very casually in everyday American English. It simply means maximum efficiency.');

make_entry('The last straw', 'Idioms and Phrases', 'The final problem or annoyance in a series that causes someone to lose patience or reach a breaking point.', '"The last straw" (also "the straw that broke the camel\'s back") refers to the final, often small, thing that pushes someone over the edge after a series of frustrations or problems have already built up.', '"I\'d been frustrated with my job for months, but when they cancelled our vacation days, that was the last straw — I quit." | "His constant lateness was annoying, but forgetting our anniversary was the last straw."', 'From the image of a camel carrying a heavy load — the animal can bear a lot of weight, but adding even one final straw (piece of hay) breaks its back. The idea is that the breaking point comes from accumulation.');

make_entry('Hit the nail on the head', 'Idioms and Phrases', 'To describe, identify, or do something exactly right.', '"Hitting the nail on the head" means saying or doing exactly the right thing — identifying a problem precisely or making an observation that is completely accurate.', '"You really hit the nail on the head with that analysis — that\'s exactly what the problem is." | "When she said the issue was communication, she hit the nail on the head."', 'From carpentry — hitting a nail precisely on its head drives it in cleanly and efficiently. Missing the head wastes effort and bends the nail. The metaphor captures the idea of precision and exactness.');

make_entry('Under the table', 'Idioms and Phrases', 'Done secretly or illegally, especially referring to payments made without official records.', '"Under the table" refers to transactions or arrangements that are hidden, unofficial, or illegal — particularly cash payments that are not reported to tax authorities or employers.', '"He paid the workers under the table to avoid taxes." | "The landlord wanted to be paid under the table, which made me nervous."', 'The image is of a handshake or payment happening literally under a table, hidden from view. Used to describe any kind of hidden or unofficial arrangement, but most commonly applied to unreported cash payments.');

// ── Vocabulary ────────────────────────────────────────────────
make_entry('Eloquent', 'Vocabulary', 'Fluent, persuasive, and expressive in speech or writing.', '"Eloquent" describes someone who speaks or writes in a clear, effective, and beautiful way — using language skillfully to express ideas and move people. An eloquent speaker chooses words carefully and delivers them with power.', '"Her eloquent speech at the ceremony moved everyone in the audience." | "He wrote an eloquent letter explaining his decision to resign."', 'A high compliment in English. "Eloquence" is considered a rare and admirable quality. It combines clarity, beauty, and persuasion in a single word.');

make_entry('Ambiguous', 'Vocabulary', 'Open to more than one interpretation; not clear or definite in meaning.', '"Ambiguous" describes something that can be understood in more than one way — it is unclear which meaning is intended. Ambiguity can be accidental (poor communication) or intentional (keeping options open).', '"The contract language was ambiguous, so both sides interpreted it differently." | "His response was deliberately ambiguous — he didn\'t want to commit either way."', 'From Latin "ambiguus" meaning "moving from side to side." An important word in law, writing, and business communication. Ambiguity in legal documents and agreements often leads to disputes.');

make_entry('Concise', 'Vocabulary', 'Giving a lot of information clearly and in few words; brief but comprehensive.', '"Concise" means expressing something clearly and fully without unnecessary words. It is the opposite of verbose or wordy. Being concise is highly valued in professional writing and communication.', '"Please send a concise summary — no more than one page." | "His presentation was concise and powerful — he made his point in five minutes."', 'One of the most praised qualities in business writing. "Be concise" is the advice given in virtually every writing guide. It does not mean short — it means no wasted words.');

make_entry('Meticulous', 'Vocabulary', 'Showing great attention to detail; very careful and precise.', '"Meticulous" describes someone who pays extremely careful attention to every detail, making sure everything is exactly right. It implies thoroughness and precision.', '"She is meticulous about proofreading — she catches every typo." | "The meticulous planning paid off — the event went perfectly."', 'From Latin "metus" meaning fear — originally it implied being careful out of fear of making mistakes. Now it simply means extremely careful and detail-oriented. A positive quality in most professional contexts.');

make_entry('Tenacious', 'Vocabulary', 'Determined and persistent; not giving up easily.', '"Tenacious" describes someone who holds on firmly to their goals and does not give up despite obstacles or setbacks. It implies strength of purpose and persistence.', '"She is tenacious in her pursuit of excellence — she never accepts mediocre work." | "You need to be tenacious in this industry — it takes years to break through."', 'From Latin "tenax" meaning holding fast. A strong, positive word for persistence. Different from stubborn — tenacious implies purposeful, admirable persistence rather than pig-headed refusal to change.');

make_entry('Verbose', 'Vocabulary', 'Using more words than necessary; overly wordy.', '"Verbose" describes writing or speech that uses far more words than needed to convey its meaning. It is the opposite of concise. Verbose communication obscures the message and wastes the reader\'s or listener\'s time.', '"The report was so verbose that the key findings were buried on page 12." | "Try not to be verbose in your emails — get to the point quickly."', 'From Latin "verbosus" meaning full of words. Usually used critically. Good business writing aims to avoid verbosity. If you can say something in 10 words instead of 50, the 10-word version is almost always better.');

make_entry('Empathy', 'Vocabulary', 'The ability to understand and share the feelings of another person.', '"Empathy" is the capacity to put yourself in someone else\'s position and genuinely understand what they are feeling. It is deeper than sympathy (feeling sorry for someone) — it involves actually feeling with them.', '"Great customer service requires empathy — you need to understand the customer\'s frustration." | "She showed real empathy when her colleague lost his job."', 'One of the most important emotional intelligence terms. Distinguishing empathy (feeling with someone) from sympathy (feeling for someone) is an important distinction in counseling, leadership, and everyday communication.');

make_entry('Integrity', 'Vocabulary', 'The quality of being honest and having strong moral principles; moral uprightness.', '"Integrity" refers to consistency between one\'s values and one\'s actions — doing the right thing even when no one is watching. It implies honesty, reliability, and moral strength.', '"We hire people with integrity — we need people who will do the right thing even when it\'s difficult." | "She showed integrity by reporting the billing error even though it cost her department money."', 'One of the most commonly cited values in American workplace culture. "Integrity" appears in virtually every company\'s stated values. It is also used in a structural sense — "structural integrity" means a structure is sound and undamaged.');

// ── Everyday American Expressions ────────────────────────────
make_entry('What\'s up?', 'Everyday American Expressions', 'A very casual greeting meaning "how are you?" or "what is happening?"', '"What\'s up?" is one of the most common casual American greetings. Like "how\'s it going?", it is usually not a genuine question — it is a social greeting. The expected response is brief and casual, not a detailed explanation.', 'Passing someone in the hall: "Hey, what\'s up?" → "Not much, you?" | Starting a casual conversation: "What\'s up? Haven\'t seen you in a while!"', 'One of the quintessential casual American greetings. It can also sometimes be a genuine question — "what\'s up?" can mean "what is going on?" or "is something wrong?" depending on tone and context.');

make_entry('My bad', 'Everyday American Expressions', 'An informal way of saying "my mistake" or "I\'m sorry, that was my fault."', '"My bad" is a very casual admission of fault or mistake. It is shorter and more informal than "I\'m sorry" or "that was my fault." It is used for small mistakes in casual settings.', '"Oh, I thought the meeting was at 3 — my bad, it\'s at 2." | "My bad for not telling you earlier — I completely forgot."', 'Became popular in American English in the 1980s-90s, partly through basketball culture. It is very casual — appropriate among friends and colleagues but too informal for formal apologies or professional situations with clients.');

make_entry('For real?', 'Everyday American Expressions', 'Expressing surprise or asking for confirmation that something is true.', '"For real?" expresses genuine surprise or disbelief, and asks the other person to confirm they are being serious. It is the casual equivalent of "really?" or "are you serious?"', '"They\'re giving everyone a bonus?" → "For real?! That\'s amazing!" | "The concert got cancelled." → "For real? I already bought tickets!"', 'Very common in casual American speech, especially among younger generations. Can also be used as a statement — "For real, that was the best pizza I\'ve ever had" — meaning "I am being completely serious."');

make_entry('Hang out', 'Everyday American Expressions', 'To spend time casually with someone without a specific purpose or agenda.', '"Hanging out" means spending informal, relaxed time with friends or family — not for a specific goal, just to enjoy each other\'s company. It is the American equivalent of "spending time together" in a casual way.', '"Do you want to hang out this weekend?" | "We just hung out at his place, watched movies, nothing special."', 'A very common American phrase for casual socializing. "Hang out" as a noun (a hangout) refers to a place where people gather casually. Different from a formal get-together or a planned event.');

make_entry('Chill out', 'Everyday American Expressions', 'To relax and calm down; to stop being stressed, anxious, or upset.', '"Chill out" is a casual instruction or suggestion to relax, calm down, or stop overreacting. It can be said to oneself or to others. "Chill" by itself has the same meaning.', '"Chill out — it\'s just a small mistake, we can fix it." | "I just need to go home and chill out after this week."', '"Chill" and "chill out" are extremely versatile in American English. "She\'s pretty chill" means she is relaxed and easy-going. "Are you chill with that?" means "are you okay with that?" It can be a verb, adjective, or noun.');

make_entry('Grab a bite', 'Everyday American Expressions', 'To get something to eat, usually informally and quickly.', '"Grabbing a bite" means getting a quick, informal meal — not a sit-down dinner, but something fast and casual. It implies spontaneity and informality.', '"Do you want to grab a bite before the movie?" | "I\'m starving — let\'s grab a bite somewhere."', '"Grab" is used very commonly in casual American English to mean doing something quickly and informally — "grab a coffee," "grab a seat," "grab a minute." It implies ease and spontaneity.');

// ── Politeness and Tone ───────────────────────────────────────
make_entry('I was wondering if...', 'Politeness and Tone', 'A very polite way to make a request, suggesting you have been thinking about it and are not demanding.', '"I was wondering if..." is one of the softest, most indirect ways to make a request in American professional English. It frames the request as something you have been thinking about, making it feel less like a demand.', '"I was wondering if you\'d have time to review my draft this week." | "I was wondering if we could move the meeting to Thursday?"', 'The past tense ("was wondering" rather than "am wondering") adds an extra layer of softness and politeness. This construction is very common in professional emails when making requests of people above you in the hierarchy.');

make_entry('Would it be possible to...', 'Politeness and Tone', 'A formal, polite way to make a request, framing it as a question about feasibility rather than a demand.', '"Would it be possible to..." is a formal request construction that softens a demand into a question about whether something can be done. It is respectful and gives the other person room to say no.', '"Would it be possible to get the report by Friday?" | "Would it be possible to schedule a call this week to discuss the proposal?"', 'This construction is particularly useful when making requests of senior people, clients, or anyone you need to be especially respectful with. It is more formal than "could you please" and very appropriate for professional email.');

make_entry('I appreciate your patience', 'Politeness and Tone', 'A polite acknowledgment that someone has been waiting or dealing with a delay, expressing gratitude for their understanding.', '"I appreciate your patience" is a professional phrase used when you have kept someone waiting or caused a delay. It acknowledges the inconvenience and thanks them for not complaining about it.', '"I appreciate your patience while we processed your request — it is now complete." | "Thank you for your patience — I know this took longer than expected."', 'Common in customer service, email responses to delayed inquiries, and any professional situation where someone has had to wait. It is more warm and personal than just saying "sorry for the delay."');

make_entry('Let me know if you need anything', 'Politeness and Tone', 'A friendly offer of continued help or support, typically used at the end of a conversation or email.', '"Let me know if you need anything" is a standard American professional closing that offers ongoing availability and help. It signals openness and a willingness to assist further.', '"The package has shipped — let me know if you need anything else." | "Happy to help with the presentation. Let me know if you need anything."', 'One of the most common closing lines in American professional emails. It is warm without being over-the-top, and signals that the relationship continues beyond this single transaction. Often paired with "feel free to reach out."');

make_entry('Feel free to...', 'Politeness and Tone', 'A polite invitation giving someone permission or encouragement to do something without feeling hesitant.', '"Feel free to..." gives the other person explicit permission and encouragement to take an action — ask a question, reach out, visit, etc. It removes hesitation by preemptively saying it is okay.', '"Feel free to reach out if you have any questions." | "Feel free to take a look at the document and add your comments."', 'Extremely common in American professional communication. It is a gracious phrase that makes the other person feel welcome and comfortable taking an action they might otherwise hesitate to take.');

// ── Cultural Context ──────────────────────────────────────────
make_entry('Take a rain check', 'Cultural Context', 'Declining an offer now but expressing interest in doing it another time.', 'While "rain check" is also general American lingo, in cultural context it is worth understanding that this phrase is deeply embedded in American social behavior — the polite way to say no without fully closing the door.', '"We\'d love to come to your barbecue, but we already have plans. Can we take a rain check?" | "Want to grab coffee?" → "I\'m slammed today — can I take a rain check?"', 'Originally a literal ticket given to baseball fans when games were rained out. In American social culture, offering and accepting rain checks is a standard part of polite social navigation — it\'s a way of saying "no, but I genuinely want to yes later."');

make_entry('Touch wood', 'Cultural Context', 'Said while knocking on wood to avoid jinxing good luck or to ward off bad outcomes after saying something optimistic.', 'Americans say "knock on wood" (not "touch wood" as the British say) when they want to avoid jinxing something after making an optimistic statement. The superstition is that acknowledging good fortune might cause it to reverse.', '"The project is going really well so far — knock on wood." | "I haven\'t been sick all winter, knock on wood."', 'The American version is "knock on wood" — you literally knock on a wooden surface while saying it. The British say "touch wood." Both come from ancient superstitions about spirits living in trees. Still widely used even by people who don\'t actually believe in superstitions.');

make_entry('Tailgate', 'Cultural Context', 'A party held in a parking lot before a sports game, usually involving food, drinks, and socializing from the back of a pickup truck or SUV.', 'Tailgating is a uniquely American social tradition where fans gather in stadium parking lots before a game to eat, drink, and socialize. The name comes from the tailgate (the back door) of pickup trucks and station wagons, which were lowered and used as a party surface.', '"We got to the stadium three hours early to tailgate before the game." | "The tailgate was almost as fun as the game itself — amazing food and great company."', 'Tailgating is a beloved American tradition closely tied to football culture. It has expanded beyond sports — "tailgate parties" now happen before concerts and other events. If someone invites you to tailgate, expect grills, coolers, folding chairs, and a lot of food.');

make_entry('Potluck', 'Cultural Context', 'A meal where each guest brings a dish to share with the group.', 'A potluck is a very common American social gathering format where the food is contributed collectively — each person or family brings one dish, and everyone shares. The host provides the space; the guests provide the food.', '"We\'re having a potluck for Thanksgiving — bring your famous mac and cheese!" | "The office is doing a holiday potluck — sign up for what you\'re bringing."', 'Potlucks are extremely common at American offices, churches, neighborhood events, and holiday gatherings. There\'s usually a sign-up sheet so dishes are coordinated (appetizers, mains, sides, desserts). If invited, always bring something — coming empty-handed is considered rude.');

make_entry('RSVP', 'Cultural Context', 'Please respond to an invitation to indicate whether you will attend.', 'RSVP is French for "répondez s\'il vous plaît" (please respond). In American usage, it means the host needs to know if you are coming so they can plan food, seating, and other logistics. RSVPing is considered a social obligation.', '"The invitation says RSVP by October 1st." | "I need to RSVP to the wedding — I keep forgetting to send back the card."', 'In American culture, failing to RSVP is considered rude. Hosts need accurate headcounts for catering, seating, and costs. "RSVP regrets only" means you only need to respond if you CANNOT attend — if you say nothing, the host assumes you\'re coming.');

make_entry('Black Friday', 'Cultural Context', 'The day after Thanksgiving, traditionally the biggest shopping day of the year in the United States.', 'Black Friday is the Friday after Thanksgiving (the fourth Thursday of November) and marks the beginning of the holiday shopping season. Retailers offer massive discounts, and stores open very early — sometimes at midnight or even Thanksgiving evening.', '"I got a great deal on a TV — 50% off on Black Friday." | "I refuse to go to the mall on Black Friday — the crowds are insane."', '"Black Friday" got its name because it was traditionally the day when retailers\' books would go from "in the red" (loss) to "in the black" (profit) for the year. Now the deals have extended to "Cyber Monday" (online deals the following Monday) and even entire weeks of sales.');

// ── Kids and School English ───────────────────────────────────
make_entry('Homeroom', 'Kids and School English', 'A class period at the start of the school day where students gather for attendance, announcements, and administrative tasks.', 'Homeroom is a short period at the beginning of the school day — typically 10-20 minutes — where students in the same assigned group gather. Attendance is taken, announcements are made, and administrative tasks are handled. It is not a subject class.', '"My homeroom teacher is Mr. Johnson — he takes attendance and makes announcements every morning." | "We get our report cards in homeroom at the end of the semester."', 'Homeroom is common in American middle schools and high schools. In elementary school, students usually stay with one teacher all day, so a separate homeroom period is less common. "Homeroom teacher" is the teacher assigned to your homeroom group.');

make_entry('Parent-teacher conference', 'Kids and School English', 'A scheduled meeting between a child\'s parents and their teacher to discuss the child\'s academic progress and behavior.', 'Parent-teacher conferences are formal meetings where parents meet one-on-one with their child\'s teacher to discuss academic performance, social behavior, and any concerns. They are usually held once or twice a year.', '"Parent-teacher conferences are next week — I need to sign up for a time slot." | "The teacher wants to discuss Tommy\'s reading progress at the parent-teacher conference."', 'These meetings are standard in American schools. Parents typically sign up for 15-20 minute appointment slots. It is considered important to attend. Failing to show up for conferences can signal lack of engagement to teachers. Some schools now also offer virtual conferences.');

make_entry('Honor roll', 'Kids and School English', 'A list of students who have achieved high academic grades, published by the school each semester.', 'The honor roll is a list of students who have earned sufficiently high grades to receive academic recognition. Being "on the honor roll" is a source of pride for students and families. There are often different levels — Honor Roll and High Honor Roll, for example.', '"She made the honor roll every semester in middle school." | "The school publishes the honor roll in the local newspaper at the end of each term."', 'Honor roll recognition is common in American schools from elementary through high school. It is often used on college applications to demonstrate academic consistency. Some families display "My child is an honor roll student" bumper stickers on their cars — a common American phenomenon.');

make_entry('Extracurricular activities', 'Kids and School English', 'Activities students participate in outside of regular academic classes, such as sports, clubs, music, and arts.', 'Extracurricular activities are all the things students do beyond their required academic coursework — sports teams, school newspaper, drama club, student government, debate team, music ensembles, and more. They are important for college applications and personal development.', '"She\'s involved in a lot of extracurriculars — soccer, yearbook, and the science club." | "American colleges look at extracurricular activities, not just grades."', 'In American education, well-roundedness is highly valued. Strong extracurricular participation can significantly help college applications. Many families carefully plan their children\'s extracurriculars from early in high school. The word is often shortened to "extracurriculars" or just "activities."');

make_entry('School supply list', 'Kids and School English', 'A list of materials and supplies that students are required to bring to school at the start of the year.', 'Every August before school starts, American schools send home (or post online) a list of specific supplies each student must bring. Lists vary by grade and teacher and can include everything from pencils and folders to specific brands of crayons or composition notebooks.', '"I need to go shopping — the school supply list just came out." | "The teacher wants wide-ruled notebooks, not college-ruled — it\'s on the supply list."', 'Back-to-school shopping for supplies is a major American cultural event in August. Stores like Target, Walmart, and Staples have large back-to-school sections. Parents often spend $50-$150+ per child on supplies. Supply lists can be very specific — sometimes down to the brand and color of folders required.');

// ── Indian English vs American English ───────────────────────
make_entry('Cousin brother / Cousin sister', 'Indian English vs American English', 'In Indian English, male cousins are called "cousin brothers" and female cousins are called "cousin sisters." In American English, all cousins are simply called "cousins."', 'In Indian English, it is common to specify the gender and relationship by saying "cousin brother" or "cousin sister." This is a direct translation from Indian languages where such distinctions are made. In American English, "cousin" is gender-neutral and no modifier is needed.', 'Indian English: "My cousin brother is visiting from Bangalore." | American English: "My cousin is visiting from Bangalore."', 'Americans find the terms "cousin brother" and "cousin sister" unusual and might wonder what relationship you are describing. The word "cousin" in American English covers both male and female cousins. Other relationship terms also work differently — Indians say "maternal uncle" where Americans just say "uncle."');

make_entry('Passed out', 'Indian English vs American English', 'In Indian English, "passed out" means graduated from a school or college. In American English, "passed out" means fainted or lost consciousness.', 'This is one of the most important differences to know because it can cause real confusion. In India, "I passed out from IIT" means "I graduated from IIT." In America, "I passed out" means "I fainted" or "I lost consciousness." The American meaning can make Indian usage sound alarming.', 'Indian English: "He passed out from Delhi University in 2015." | American English: "He graduated from Delhi University in 2015." | American meaning of passed out: "She passed out in the heat and had to be taken to the hospital."', 'This difference has caused genuine confusion and even concern when Indians use it with American colleagues. Always use "graduated" when speaking with Americans. The phrase "passed out from" as meaning graduated is specific to Indian English.');

make_entry('Out of station', 'Indian English vs American English', 'In Indian English, "out of station" means away from one\'s home city or workplace. In American English, this phrase is not used — Americans say "out of town" or "away."', '"Out of station" is a very common Indian English phrase meaning someone is traveling or away from their base location. It is widely understood throughout India but completely unknown in American English.', 'Indian English: "Sorry, I was out of station last week." | American English: "Sorry, I was out of town last week." or "I was away last week."', '"Out of station" sounds puzzling to Americans, who associate "station" with a train station or police station. "Out of town" is the standard American equivalent. "I\'m traveling" or "I was away" also work perfectly.');

make_entry('Good name', 'Indian English vs American English', 'In Indian English, asking someone\'s "good name" is a polite way of asking their name. In American English, people simply ask "what is your name?"', 'The phrase "may I know your good name?" or "what is your good name?" is a polite form of address in Indian English, reflecting the Indian cultural tradition of showing respect by adding an honorific quality to the question. Americans simply say "what\'s your name?"', 'Indian English: "Excuse me, may I know your good name?" | American English: "Excuse me, what\'s your name?" or "I\'m sorry, I didn\'t catch your name."', 'The "good" prefix does not add meaning in American English — all names are simply "names." When Indians use this phrase with Americans, Americans sometimes get confused, wondering if there is a "bad name" to contrast with. It is charming but signals a strong Indian English influence.');

// ── Common Confusing Words ────────────────────────────────────
make_entry('Fewer vs Less', 'Common Confusing Words', 'Use "fewer" for things you can count individually; use "less" for quantities that cannot be counted individually.', 'The rule: use "fewer" when you can count the individual items (fewer books, fewer people, fewer mistakes). Use "less" when the quantity is measured rather than counted (less water, less time, less money). A common error is using "less" when "fewer" is correct.', 'Correct: "There are fewer students in this class than last year." | Correct: "I have less patience today than yesterday." | Common error: "Express lane: 10 items or less" (should be "10 items or fewer").', 'The grocery store "10 items or less" sign is one of the most cited examples of this error. Grammar sticklers notice it everywhere. The distinction is becoming less strict in casual speech, but in formal writing, maintaining the difference is important.');

make_entry('Its vs It\'s', 'Common Confusing Words', '"Its" is the possessive form of "it." "It\'s" is a contraction of "it is" or "it has."', 'This is one of the most common punctuation errors in English. "Its" (no apostrophe) shows possession — something belonging to "it." "It\'s" (with apostrophe) is a contraction — short for "it is" or "it has." A quick test: can you replace it with "it is"? If yes, use "it\'s." If no, use "its."', 'Correct: "The dog wagged its tail." (possession — the tail belongs to the dog) | Correct: "It\'s raining outside." (= "It is raining") | Common error: "The company lost it\'s market share." (should be "its")', 'The apostrophe in "it\'s" does NOT show possession — it shows a missing letter. This is confusing because apostrophes DO show possession in most other cases (John\'s book, the company\'s policy). "It\'s" is the one major exception. Reading it as "it is" in your head helps catch the error.');

make_entry('Their, There, They\'re', 'Common Confusing Words', '"Their" shows possession. "There" refers to a place or introduces a statement. "They\'re" is a contraction of "they are."', 'Three words that sound identical but have completely different meanings and uses. "Their" = belonging to them. "There" = in that place, or used to introduce a sentence. "They\'re" = they are. These are among the most commonly confused words in English writing.', 'Their: "The students left their books on the table." | There: "The restaurant is right there." / "There are three options." | They\'re: "They\'re going to be late."', 'A quick test for each: Can you replace it with "they are"? Use "they\'re." Does it show belonging? Use "their." Is it about a place? Use "there." These errors are very common in informal writing and are noticed by careful readers.');

make_entry('Compliment vs Complement', 'Common Confusing Words', '"Compliment" means praise or an expression of admiration. "Complement" means something that goes well with something else and makes it complete or better.', '"Compliment" (with an "i") is what you give when you tell someone they look nice or did a great job. "Complement" (with an "e") is what one thing does to another when they work well together — they enhance each other.', 'Compliment: "She gave him a compliment on his presentation." | Complement: "The wine complements the cheese perfectly." | Common confusion: "That scarf really complements your outfit" (NOT compliments — it works well with it).', 'Memory trick: a compliment is something "I" give (both have the letter "i"). Complement comes from "complete" — when two things complement each other, they complete each other. This pair is one of the most commonly confused in professional writing.');

make_entry('Principal vs Principle', 'Common Confusing Words', '"Principal" can mean the head of a school or the most important thing. "Principle" means a fundamental rule, belief, or standard of behavior.', '"Principal" (ending in "al") is a noun for the head of a school, or an adjective meaning main/most important. "Principle" (ending in "le") refers to a fundamental rule, value, or standard.', 'Principal (school): "The principal called my parents for a meeting." | Principal (main): "The principal reason for the delay was supply chain issues." | Principle: "She refused to compromise her principles." | Principle: "The principle of supply and demand drives pricing."', 'Memory trick: the principal is your "pal" (ends in "pal"). A principle is a "rule" (both end in "le"). This pair commonly appears in business writing — "a matter of principle" vs. "the principal stakeholders."');

// ── Literal Translation Traps ─────────────────────────────────
make_entry('Do one thing', 'Literal Translation Traps', 'In Indian English, "do one thing" is used to introduce a suggestion. In American English, this phrase sounds strange — Americans would just state the suggestion directly.', '"Do one thing" is a very common way of introducing advice or a suggestion in Indian English. It comes from a direct translation of phrases in Hindi, Bengali, and other Indian languages. In American English, no such introductory phrase is used — the suggestion is stated directly.', 'Indian English: "Do one thing — call the helpdesk and they will fix it." | American English: "Just call the helpdesk — they\'ll fix it." or "You should call the helpdesk."', 'This phrase sounds odd to Americans because it implies the person should do only one thing among many possibilities, which is not the intended meaning. It is simply a conversational habit from translation. Americans would find "you should..." or "try..." or "just..." more natural.');

make_entry('Homely', 'Literal Translation Traps', 'In Indian English, "homely" means warm, simple, and domestic — like home. In American English, "homely" means plain-looking or unattractive.', 'This is one of the most important false friends between Indian and American English. In India, calling someone "homely" is a compliment — it means they have domestic qualities, are family-oriented and warm. In America, calling someone "homely" means they are physically unattractive. This difference can cause serious offense.', 'Indian English meaning: "She is very homely — a wonderful cook and very family-oriented." | American English meaning: "He described her as homely, which hurt her feelings." (meaning plain or unattractive)', 'This is a classic "false friend" — a word that exists in both varieties of English but means very different things. Always use "family-oriented," "domestic," or "warm and welcoming" when you want to convey the Indian English meaning of homely to an American audience.');

make_entry('Kindly', 'Literal Translation Traps', 'In Indian English, "kindly" is commonly used as a formal substitute for "please." In American English, "kindly" sounds unusually formal or even cold when used this way.', '"Kindly" as a request word is standard in Indian formal writing — "kindly send the report," "kindly confirm attendance." In American English, "please" is the standard request word. "Kindly" in American usage often sounds stiff, formal, or even slightly condescending.', 'Indian English: "Kindly revert at the earliest." | American English: "Please reply as soon as you can." | Note: Americans might use "kindly" sarcastically: "Kindly remove your belongings from my desk" can sound passive-aggressive in American English.', '"Kindly" in American professional emails can read as passive-aggressive or overly stiff. Stick to "please" in American professional communication. "Kindly" is not wrong in formal contexts, but it sounds unusual and might give the wrong tone.');

$count = \Drupal::entityTypeManager()->getStorage('node')
  ->getQuery()->condition('type', 'language_entry')->count()->execute();
echo "\nTotal language entries now: $count\n";
