<?php

use Drupal\node\Entity\Node;

function get_cat($name) {
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')
    ->loadByProperties(['vid' => 'main_categories', 'name' => $name]);
  return $terms ? reset($terms)->id() : NULL;
}

$entries = [
  ['title' => 'Low-hanging fruit', 'category' => 'Business Lingo', 'short_meaning' => 'The easiest tasks or opportunities that can be achieved quickly with minimal effort.', 'detailed_explanation' => 'In business, "low-hanging fruit" refers to tasks, goals, or opportunities that are easy to accomplish and can deliver quick results. Just like fruit that hangs low on a tree is the easiest to pick, low-hanging fruit in business means starting with the simplest wins before tackling harder challenges.', 'usage_examples' => '"Before we redesign the entire website, let\'s go after the low-hanging fruit — fixing the checkout page should increase sales immediately."', 'notes' => 'This phrase is extremely common in corporate settings, especially in strategy meetings and project planning. Some people consider it overused business jargon.'],
  ['title' => 'Take it offline', 'category' => 'Business Lingo', 'short_meaning' => 'To move a detailed or side discussion out of the current meeting to a separate, smaller conversation.', 'detailed_explanation' => 'When someone says "let\'s take this offline," they mean the current topic is too detailed or only relevant to a few people — so it should be discussed separately rather than taking up everyone\'s time in the meeting.', 'usage_examples' => '"That\'s a great question about the budget details, but let\'s take it offline — I\'ll set up a call with you and the finance team this afternoon."', 'notes' => 'Despite the word "offline," this has nothing to do with the internet. It comes from the idea of stepping away from the main discussion. Often used to politely end a rabbit hole in a meeting.'],
  ['title' => 'Bandwidth', 'category' => 'Business Lingo', 'short_meaning' => 'In workplace language, a person\'s available time and capacity to take on additional work.', 'detailed_explanation' => 'Originally a technical term from networking, "bandwidth" has been widely adopted in business to describe how much capacity a person or team has. Saying you don\'t have the bandwidth means you are too busy.', 'usage_examples' => '"I would love to help with that project, but I do not have the bandwidth right now — my plate is full through the end of the quarter."', 'notes' => 'This tech metaphor is now mainstream in corporate language everywhere from startups to large corporations.'],
  ['title' => 'No worries', 'category' => 'American Lingo', 'short_meaning' => 'A casual way to say "it\'s okay," "don\'t apologize," or "you\'re welcome."', 'detailed_explanation' => '"No worries" is one of the most common casual responses in American English. It can be a response to an apology, a thank you, or a concern. It signals that everything is fine and there is nothing to be stressed about.', 'usage_examples' => '"Sorry I\'m a few minutes late!" → "No worries at all, we just started." | "Thanks for helping me." → "No worries, happy to help!"', 'notes' => 'Originally popular in Australian English, it spread widely into American casual speech. It is warmer and more relaxed than "no problem" or "you\'re welcome."'],
  ['title' => 'Hang tight', 'category' => 'American Lingo', 'short_meaning' => 'Please wait a moment; stay where you are and be patient.', 'detailed_explanation' => '"Hang tight" is a casual American expression used to ask someone to wait patiently for a short time. It implies the wait will not be long and the situation is under control.', 'usage_examples' => '"Hang tight, I\'ll be with you in just a second." | "Hang tight — the system is loading and should be ready in a minute."', 'notes' => 'Similar to "hold on" but warmer and more reassuring. Very common in customer service, casual conversations, and workplace settings.'],
  ['title' => 'Achilles\' heel', 'category' => 'Idioms and Phrases', 'short_meaning' => 'A person\'s or organization\'s single critical weakness, despite overall strength.', 'detailed_explanation' => 'An "Achilles\' heel" refers to a small but crucial vulnerability that can cause failure despite great overall strength. It can describe a person, a system, or a company that is strong overall but has one significant weak point.', 'usage_examples' => '"The company\'s Achilles\' heel is its dependence on a single supplier." | "Math has always been my Achilles\' heel."', 'notes' => 'From Greek mythology: Achilles was a great warrior whose entire body was invulnerable except for his heel. He was eventually killed by an arrow to that spot.'],
  ['title' => 'Break the ice', 'category' => 'Idioms and Phrases', 'short_meaning' => 'To do or say something to reduce tension and make people feel more comfortable at the start of a social situation.', 'detailed_explanation' => '"Breaking the ice" means taking the first step to start a conversation or make a tense or awkward situation feel more relaxed. It is commonly used in social settings, meetings, or new relationships.', 'usage_examples' => '"The new manager told a funny story about himself to break the ice on his first day." | "We played a quick game to break the ice before the workshop."', 'notes' => 'This phrase comes from old practice of sending smaller icebreaker ships ahead of larger vessels to break up frozen waterways. "Icebreaker activities" are still commonly used in corporate training.'],
  ['title' => 'Spill the beans', 'category' => 'Idioms and Phrases', 'short_meaning' => 'To accidentally or intentionally reveal secret or private information.', 'detailed_explanation' => 'When someone "spills the beans," they reveal information that was meant to be kept secret — usually accidentally. It can also be used when someone decides to share the truth after keeping it hidden.', 'usage_examples' => '"Don\'t spill the beans about the surprise party!" | "He finally spilled the beans about why he left the company."', 'notes' => 'The origin is debated — one theory links it to ancient Greek voting using beans. Regardless of origin, it is widely used in both casual and slightly formal settings in American English.'],
  ['title' => 'Prepone', 'category' => 'Indian English vs American English', 'short_meaning' => 'To move a meeting or event to an earlier time. Used in Indian English but does not exist in American English.', 'detailed_explanation' => 'In Indian English, "prepone" is used as the opposite of "postpone." However, this word does not exist in American or British English. Americans say "move up" or "reschedule to an earlier time" instead.', 'usage_examples' => 'Indian English: "Can we prepone the meeting to 9 AM?" | American English: "Can we move the meeting up to 9 AM?"', 'notes' => '"Prepone" is perfectly logical and widely understood in India, but using it in an American workplace will cause confusion — most Americans have never heard it.'],
  ['title' => 'Do the needful', 'category' => 'Indian English vs American English', 'short_meaning' => 'Please do what is necessary. Common in Indian English but sounds unusual in American English.', 'detailed_explanation' => '"Do the needful" is used in Indian professional emails to ask someone to take necessary action. While clear and polite in Indian English, it sounds old-fashioned or overly formal to most Americans, who would simply say "please handle this" or "please take care of this."', 'usage_examples' => 'Indian English: "Please do the needful and send the report by Friday." | American English: "Please take care of this — the report is due Friday."', 'notes' => 'This phrase appears frequently in Indian corporate emails. Replacing it with simpler alternatives will make communication feel more natural to American colleagues.'],
  ['title' => 'Revert back', 'category' => 'Indian English vs American English', 'short_meaning' => 'In Indian English, "revert" means "reply." In standard English, it means to return to a previous state — not to reply.', 'detailed_explanation' => 'In Indian professional English, "please revert" is widely used in emails to mean "please reply." However, in American English, "revert" means to go back to a previous condition — not to reply to someone. American colleagues may be confused by this usage.', 'usage_examples' => 'Indian English: "Please revert at the earliest." | American English: "Please reply at your earliest convenience." or "Please get back to me when you can."', 'notes' => 'This is one of the most frequently noticed differences in Indian vs American professional English. Replace "revert" with "reply," "respond," or "get back to me."'],
  ['title' => 'Could you please', 'category' => 'Politeness and Tone', 'short_meaning' => 'A polite way to make a request, softer than a direct command.', 'detailed_explanation' => '"Could you please" transforms a direct instruction into a courteous request. In American workplaces, making requests this way rather than giving direct commands is generally preferred, especially in emails.', 'usage_examples' => '"Could you please review this document by tomorrow?" | "Could you please forward the meeting notes to the team?"', 'notes' => 'In American workplace communication, tone matters as much as content. Phrases like "could you please" and "I was wondering if you could" signal respect and professionalism.'],
  ['title' => 'Monday morning quarterback', 'category' => 'Cultural Context', 'short_meaning' => 'Someone who criticizes decisions after the fact, when the outcome is already known.', 'detailed_explanation' => 'A "Monday morning quarterback" watches a Sunday football game and then criticizes the quarterback\'s decisions after knowing the outcome. By extension, it describes anyone who judges decisions in hindsight.', 'usage_examples' => '"It is easy to be a Monday morning quarterback and say we should have launched the product earlier, but we did not have that information at the time."', 'notes' => 'Deeply rooted in American football culture. NFL games are played on Sundays and the quarterback is the key decision-maker. Commonly used in business to push back on hindsight criticism.'],
  ['title' => 'Potluck', 'category' => 'Cultural Context', 'short_meaning' => 'A gathering where each guest brings a dish to share, so the food is contributed collectively.', 'detailed_explanation' => 'A potluck is a very common American social tradition where everyone brings one dish and the group shares all the food. It is popular at office parties, neighborhood gatherings, and holiday celebrations.', 'usage_examples' => '"We are having a potluck lunch on Friday — sign up to bring an appetizer, main dish, or dessert."', 'notes' => 'Potlucks are very common in American workplaces especially around Thanksgiving and Christmas. If invited, it is expected you bring a dish — not attending empty-handed.'],
  ['title' => 'Field trip', 'category' => 'Kids and School English', 'short_meaning' => 'An educational trip taken by a school class to a location outside the classroom.', 'detailed_explanation' => 'A field trip is when a teacher takes the entire class on a supervised outing to a real-world location as part of their learning. Parents are usually asked to sign a permission slip before the child can attend.', 'usage_examples' => '"The second graders are going on a field trip to the science museum next Thursday." | "Do not forget to return your field trip permission slip — it is due tomorrow."', 'notes' => 'Field trips require: (1) a signed permission slip, (2) sometimes a small fee, and (3) occasionally parent chaperone volunteers.'],
  ['title' => 'Return back', 'category' => 'Literal Translation Traps', 'short_meaning' => '"Return back" is redundant — "return" already means to come back, so "back" is unnecessary.', 'detailed_explanation' => 'In many Indian languages, saying the equivalent of "return back" is grammatically natural. However, in English, "return" already contains the meaning of going back. The correct English is simply "return."', 'usage_examples' => 'Incorrect: "Please return back the documents by Monday." | Correct: "Please return the documents by Monday."', 'notes' => 'Similar redundancies: "revert back," "repeat again," and "free gift." These are understood, but native English speakers notice them.'],
];

$created = 0;
foreach ($entries as $entry) {
  $cat_id = get_cat($entry['category']);
  if (!$cat_id) { echo "Category not found: {$entry['category']}\n"; continue; }
  $node = Node::create([
    'type' => 'language_entry',
    'title' => $entry['title'],
    'status' => 1,
    'moderation_state' => 'published',
    'field_main_category' => ['target_id' => $cat_id],
    'field_short_meaning' => $entry['short_meaning'],
    'field_detailed_explanation' => ['value' => $entry['detailed_explanation'], 'format' => 'basic_html'],
    'field_usage_examples' => ['value' => $entry['usage_examples'], 'format' => 'basic_html'],
    'field_notes_background' => ['value' => $entry['notes'], 'format' => 'basic_html'],
  ]);
  $node->save();
  $created++;
  echo "Created: {$entry['title']}\n";
}
echo "\n$created entries created!\n";
